# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/DemoPJ1.xdc

# Block Designs: bd/DemoPJ1/DemoPJ1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoPJ1 || ORIG_REF_NAME==DemoPJ1}]

# IP: bd/DemoPJ1/ip/DemoPJ1_shift_register_8bit_0_0/DemoPJ1_shift_register_8bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoPJ1_shift_register_8bit_0_0 || ORIG_REF_NAME==DemoPJ1_shift_register_8bit_0_0}]

# IP: bd/DemoPJ1/ip/DemoPJ1_shift_register_8bit_1_0/DemoPJ1_shift_register_8bit_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoPJ1_shift_register_8bit_1_0 || ORIG_REF_NAME==DemoPJ1_shift_register_8bit_1_0}]

# IP: bd/DemoPJ1/ip/DemoPJ1_clk_div_0_0/DemoPJ1_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoPJ1_clk_div_0_0 || ORIG_REF_NAME==DemoPJ1_clk_div_0_0}]

# IP: bd/DemoPJ1/ip/DemoPJ1_xup_inv_0_0/DemoPJ1_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoPJ1_xup_inv_0_0 || ORIG_REF_NAME==DemoPJ1_xup_inv_0_0}]

# XDC: bd/DemoPJ1/DemoPJ1_ooc.xdc
