# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.cache/wt} [current_project]
set_property parent.project_path {D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{d:/vivado/vivado project/source_lib}} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.srcs/sources_1/bd/Demo_7Seg/Demo_7Seg.bd}}
set_property used_in_implementation false [get_files -all {{D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.srcs/sources_1/bd/Demo_7Seg/Demo_7Seg_ooc.xdc}}]
set_property is_locked true [get_files {{D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.srcs/sources_1/bd/Demo_7Seg/Demo_7Seg.bd}}]

read_verilog -library xil_defaultlib {{D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.srcs/sources_1/bd/Demo_7Seg/hdl/Demo_7Seg_wrapper.v}}
read_xdc {{D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.srcs/constrs_1/new/Demo7seg.xdc}}
set_property used_in_implementation false [get_files {{D:/vivado/vivado project/7SegDemo_1/7SegDemo_1.srcs/constrs_1/new/Demo7seg.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top Demo_7Seg_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Demo_7Seg_wrapper.dcp
catch { report_utilization -file Demo_7Seg_wrapper_utilization_synth.rpt -pb Demo_7Seg_wrapper_utilization_synth.pb }
