# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Demo7seg.xdc

# Block Designs: bd/Demo_7Seg/Demo_7Seg.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_7Seg || ORIG_REF_NAME==Demo_7Seg}]

# IP: bd/Demo_7Seg/ip/Demo_7Seg_BCD2SEG7_0_0/Demo_7Seg_BCD2SEG7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_7Seg_BCD2SEG7_0_0 || ORIG_REF_NAME==Demo_7Seg_BCD2SEG7_0_0}]

# IP: bd/Demo_7Seg/ip/Demo_7Seg_decimal_counter_0_0/Demo_7Seg_decimal_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_7Seg_decimal_counter_0_0 || ORIG_REF_NAME==Demo_7Seg_decimal_counter_0_0}]

# IP: bd/Demo_7Seg/ip/Demo_7Seg_clk_div_0_0/Demo_7Seg_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_7Seg_clk_div_0_0 || ORIG_REF_NAME==Demo_7Seg_clk_div_0_0}]

# XDC: bd/Demo_7Seg/Demo_7Seg_ooc.xdc
